=== RaCcOoN1837/CROC-Java-Course/src/com/company/Files/Input/XML/sales.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="sales" type="salesType"/>
  <xs:complexType name="entryType">
    <xs:sequence>

      <xs:element name="id" type="xs:int"/>
      <xs:element name="seller_id" type="xs:int"/>
      <xs:element name="good_id" type="xs:int"/>
      <xs:element name="amount" type="xs:int"/>
      <xs:element name="date" type="xs:date"/>

    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="salesType">
    <xs:sequence>

      <xs:element type="entryType" name="sale" maxOccurs="unbounded" minOccurs="0"/>

    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== RaCcOoN1837/CROC-Java-Course/src/com/company/files/input/xml/sales.xml
<?xml version="1.0" encoding="UTF-8" ?>
<sales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="sales.xsd">
    <sale>
        <id>1</id>
        <seller_id>1</seller_id>
        <good_id>777</good_id>
        <amount>1</amount>
        <date>2021-01-08</date>
    </sale>
    <sale>
        <id>2</id>
        <seller_id>1</seller_id>
        <good_id>666</good_id>
        <amount>3</amount>
        <date>2021-01-08</date>
    </sale>
    <sale>
        <id>3</id>
        <seller_id>5</seller_id>
        <good_id>888</good_id>
        <amount>5</amount>
        <date>2021-01-08</date>
    </sale>
    <sale>
        <id>4</id>
        <seller_id>3</seller_id>
        <good_id>222</good_id>
        <amount>1</amount>
        <date>2021-01-10</date>
    </sale>
    <sale>
        <id>5</id>
        <seller_id>7</seller_id>
        <good_id>222</good_id>
        <amount>9</amount>
        <date>2021-01-07</date>
    </sale>
    <sale>
        <id>6</id>
        <seller_id>1</seller_id>
        <good_id>999</good_id>
        <amount>4</amount>
        <date>2021-01-08</date>
    </sale>
    <sale>
        <id>7</id>
        <seller_id>2</seller_id>
        <good_id>222</good_id>
        <amount>3</amount>
        <date>2021-01-07</date>
    </sale>
    <sale>
        <id>8</id>
        <seller_id>1</seller_id>
        <good_id>555</good_id>
        <amount>2</amount>
        <date>2021-01-05</date>
    </sale>
    <sale>
        <id>9</id>
        <seller_id>4</seller_id>
        <good_id>666</good_id>
        <amount>4</amount>
        <date>2021-01-06</date>
    </sale>
    <sale>
        <id>10</id>
        <seller_id>6</seller_id>
        <good_id>444</good_id>
        <amount>2</amount>
        <date>2021-01-03</date>
    </sale>
    <sale>
        <id>11</id>
        <seller_id>4</seller_id>
        <good_id>888</good_id>
        <amount>9</amount>
        <date>2021-01-03</date>
    </sale>
    <sale>
        <id>12</id>
        <seller_id>1</seller_id>
        <good_id>999</good_id>
        <amount>8</amount>
        <date>2021-01-05</date>
    </sale>
    <sale>
        <id>13</id>
        <seller_id>4</seller_id>
        <good_id>222</good_id>
        <amount>8</amount>
        <date>2021-01-04</date>
    </sale>
    <sale>
        <id>14</id>
        <seller_id>6</seller_id>
        <good_id>777</good_id>
        <amount>3</amount>
        <date>2021-01-04</date>
    </sale>
    <sale>
        <id>15</id>
        <seller_id>6</seller_id>
        <good_id>888</good_id>
        <amount>8</amount>
        <date>2021-01-06</date>
    </sale>
    <sale>
        <id>16</id>
        <seller_id>3</seller_id>
        <good_id>555</good_id>
        <amount>4</amount>
        <date>2021-01-04</date>
    </sale>
    <sale>
        <id>17</id>
        <seller_id>6</seller_id>
        <good_id>555</good_id>
        <amount>6</amount>
        <date>2021-01-03</date>
    </sale>
    <sale>
        <id>18</id>
        <seller_id>2</seller_id>
        <good_id>444</good_id>
        <amount>4</amount>
        <date>2021-01-08</date>
    </sale>
    <sale>
        <id>19</id>
        <seller_id>6</seller_id>
        <good_id>999</good_id>
        <amount>2</amount>
        <date>2021-01-04</date>
    </sale>
    <sale>
        <id>20</id>
        <seller_id>5</seller_id>
        <good_id>555</good_id>
        <amount>2</amount>
        <date>2021-01-07</date>
    </sale>
    <sale>
        <id>21</id>
        <seller_id>3</seller_id>
        <good_id>333</good_id>
        <amount>3</amount>
        <date>2021-01-03</date>
    </sale>
    <sale>
        <id>22</id>
        <seller_id>6</seller_id>
        <good_id>888</good_id>
        <amount>2</amount>
        <date>2021-01-03</date>
    </sale>
    <sale>
        <id>23</id>
        <seller_id>2</seller_id>
        <good_id>777</good_id>
        <amount>9</amount>
        <date>2021-01-08</date>
    </sale>
    <sale>
        <id>24</id>
        <seller_id>2</seller_id>
        <good_id>555</good_id>
        <amount>9</amount>
        <date>2021-01-01</date>
    </sale>
    <sale>
        <id>25</id>
        <seller_id>1</seller_id>
        <good_id>444</good_id>
        <amount>4</amount>
        <date>2021-01-06</date>
    </sale>
    <sale>
        <id>26</id>
        <seller_id>7</seller_id>
        <good_id>444</good_id>
        <amount>3</amount>
        <date>2021-01-08</date>
    </sale>
    <sale>
        <id>27</id>
        <seller_id>4</seller_id>
        <good_id>111</good_id>
        <amount>4</amount>
        <date>2021-01-03</date>
    </sale>
    <sale>
        <id>28</id>
        <seller_id>5</seller_id>
        <good_id>777</good_id>
        <amount>7</amount>
        <date>2021-01-04</date>
    </sale>
    <sale>
        <id>29</id>
        <seller_id>4</seller_id>
        <good_id>444</good_id>
        <amount>8</amount>
        <date>2021-01-02</date>
    </sale>
    <sale>
        <id>30</id>
        <seller_id>5</seller_id>
        <good_id>333</good_id>
        <amount>5</amount>
        <date>2021-01-07</date>
    </sale>
    <sale>
        <id>31</id>
        <seller_id>3</seller_id>
        <good_id>222</good_id>
        <amount>1</amount>
        <date>2021-01-04</date>
    </sale>
    <sale>
        <id>32</id>
        <seller_id>4</seller_id>
        <good_id>555</good_id>
        <amount>3</amount>
        <date>2021-01-05</date>
    </sale>
    <sale>
        <id>33</id>
        <seller_id>7</seller_id>
        <good_id>999</good_id>
        <amount>4</amount>
        <date>2021-01-08</date>
    </sale>
    <sale>
        <id>34</id>
        <seller_id>2</seller_id>
        <good_id>444</good_id>
        <amount>2</amount>
        <date>2021-01-03</date>
    </sale>
    <sale>
        <id>35</id>
        <seller_id>6</seller_id>
        <good_id>333</good_id>
        <amount>8</amount>
        <date>2021-01-04</date>
    </sale>
    <sale>
        <id>36</id>
        <seller_id>1</seller_id>
        <good_id>777</good_id>
        <amount>10</amount>
        <date>2021-01-04</date>
    </sale>
    <sale>
        <id>37</id>
        <seller_id>3</seller_id>
        <good_id>333</good_id>
        <amount>3</amount>
        <date>2021-01-03</date>
    </sale>
    <sale>
        <id>38</id>
        <seller_id>5</seller_id>
        <good_id>777</good_id>
        <amount>1</amount>
        <date>2021-01-05</date>
    </sale>
    <sale>
        <id>39</id>
        <seller_id>6</seller_id>
        <good_id>111</good_id>
        <amount>3</amount>
        <date>2021-01-07</date>
    </sale>
    <sale>
        <id>40</id>
        <seller_id>6</seller_id>
        <good_id>222</good_id>
        <amount>1</amount>
        <date>2021-01-02</date>
    </sale>
    <sale>
        <id>41</id>
        <seller_id>7</seller_id>
        <good_id>444</good_id>
        <amount>6</amount>
        <date>2021-01-08</date>
    </sale>
    <sale>
        <id>42</id>
        <seller_id>3</seller_id>
        <good_id>222</good_id>
        <amount>3</amount>
        <date>2021-01-03</date>
    </sale>
    <sale>
        <id>43</id>
        <seller_id>7</seller_id>
        <good_id>666</good_id>
        <amount>4</amount>
        <date>2021-01-06</date>
    </sale>
    <sale>
        <id>44</id>
        <seller_id>4</seller_id>
        <good_id>111</good_id>
        <amount>9</amount>
        <date>2021-01-01</date>
    </sale>
    <sale>
        <id>45</id>
        <seller_id>7</seller_id>
        <good_id>777</good_id>
        <amount>4</amount>
        <date>2021-01-02</date>
    </sale>
    <sale>
        <id>46</id>
        <seller_id>2</seller_id>
        <good_id>333</good_id>
        <amount>8</amount>
        <date>2021-01-04</date>
    </sale>
    <sale>
        <id>47</id>
        <seller_id>3</seller_id>
        <good_id>555</good_id>
        <amount>4</amount>
        <date>2021-01-05</date>
    </sale>
    <sale>
        <id>48</id>
        <seller_id>4</seller_id>
        <good_id>222</good_id>
        <amount>10</amount>
        <date>2021-01-03</date>
    </sale>
    <sale>
        <id>49</id>
        <seller_id>6</seller_id>
        <good_id>444</good_id>
        <amount>7</amount>
        <date>2021-01-09</date>
    </sale>
    <sale>
        <id>50</id>
        <seller_id>7</seller_id>
        <good_id>111</good_id>
        <amount>5</amount>
        <date>2021-01-07</date>
    </sale>
    <sale>
        <id>51</id>
        <seller_id>1</seller_id>
        <good_id>555</good_id>
        <amount>9</amount>
        <date>2021-01-07</date>
    </sale>
    <sale>
        <id>52</id>
        <seller_id>7</seller_id>
        <good_id>888</good_id>
        <amount>10</amount>
        <date>2021-01-06</date>
    </sale>
    <sale>
        <id>53</id>
        <seller_id>2</seller_id>
        <good_id>111</good_id>
        <amount>4</amount>
        <date>2021-01-05</date>
    </sale>
    <sale>
        <id>54</id>
        <seller_id>1</seller_id>
        <good_id>666</good_id>
        <amount>8</amount>
        <date>2021-01-01</date>
    </sale>
    <sale>
        <id>55</id>
        <seller_id>6</seller_id>
        <good_id>999</good_id>
        <amount>5</amount>
        <date>2021-01-03</date>
    </sale>
    <sale>
        <id>56</id>
        <seller_id>4</seller_id>
        <good_id>666</good_id>
        <amount>7</amount>
        <date>2021-01-02</date>
    </sale>
    <sale>
        <id>57</id>
        <seller_id>7</seller_id>
        <good_id>111</good_id>
        <amount>7</amount>
        <date>2021-01-10</date>
    </sale>
    <sale>
        <id>58</id>
        <seller_id>3</seller_id>
        <good_id>666</good_id>
        <amount>10</amount>
        <date>2021-01-02</date>
    </sale>
    <sale>
        <id>59</id>
        <seller_id>4</seller_id>
        <good_id>444</good_id>
        <amount>5</amount>
        <date>2021-01-02</date>
    </sale>
    <sale>
        <id>60</id>
