=== RaCcOoN1837/CROC-Java-Course/src/com/company/files/input/xml/sellers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="sellers" type="sellersType"/>
  <xs:complexType name="sellerType">
    <xs:sequence>

      <xs:element name="id" type="xs:int"/>
      <xs:element name="first_name" type="xs:string"/>
      <xs:element name="last_name" type="xs:string"/>

    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="sellersType">
    <xs:sequence>

      <xs:element type="sellerType" name="seller" maxOccurs="unbounded" minOccurs="0"/>

    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== RaCcOoN1837/CROC-Java-Course/src/com/company/Files/Input/XML/sellers.xml
<?xml version="1.0" encoding="UTF-8" ?>
<sellers xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation = "sellers.xsd">
    <seller>
        <id>1</id>
        <first_name>Леонид</first_name>
        <last_name>Красилов</last_name>
    </seller>
    <seller>
        <id>2</id>
        <first_name>Павел</first_name>
        <last_name>Романов</last_name>
    </seller>
    <seller>
        <id>3</id>
        <first_name>Михаил</first_name>
        <last_name>Морозов</last_name>
    </seller>
    <seller>
        <id>4</id>
        <first_name>Валерия</first_name>
        <last_name>Колодина</last_name>
    </seller>
    <seller>
        <id>5</id>
        <first_name>Данил</first_name>
        <last_name>Бараховский</last_name>
    </seller>
    <seller>
        <id>6</id>
        <first_name>Владислав</first_name>
        <last_name>Бухтаев</last_name>
    </seller>
    <seller>
        <id>7</id>
        <first_name>Сергей</first_name>
        <last_name>Фирсов</last_name>
    </seller>
</sellers>
