=== RaCcOoN1837/CROC-Java-Course/src/com/company/files/input/xml/stock.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="stock" type="availabilityType"/>
  <xs:complexType name="entryType">
    <xs:sequence>

      <xs:element name="seller_id" type="xs:int"/>
      <xs:element name="good_id" type="xs:int"/>
      <xs:element name="amount" type="xs:int"/>
      <xs:element name="price" type="xs:int"/>

    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="availabilityType">
    <xs:sequence>

      <xs:element type="entryType" name="entry" maxOccurs="unbounded" minOccurs="0"/>

    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== RaCcOoN1837/CROC-Java-Course/src/com/company/Files/Input/XML/stock.xml
<?xml version="1.0" encoding="UTF-8" ?>
<stock xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="stock.xsd">
    <entry>
        <seller_id>1</seller_id>
        <good_id>111</good_id>
        <amount>23</amount>
        <price>45686</price>
    </entry>
    <entry>
        <seller_id>1</seller_id>
        <good_id>222</good_id>
        <amount>28</amount>
        <price>110921</price>
    </entry>
    <entry>
        <seller_id>1</seller_id>
        <good_id>333</good_id>
        <amount>24</amount>
        <price>81185</price>
    </entry>
    <entry>
        <seller_id>1</seller_id>
        <good_id>444</good_id>
        <amount>20</amount>
        <price>105033</price>
    </entry>
    <entry>
        <seller_id>1</seller_id>
        <good_id>555</good_id>
        <amount>20</amount>
        <price>52882</price>
    </entry>
    <entry>
        <seller_id>1</seller_id>
        <good_id>666</good_id>
        <amount>28</amount>
        <price>37499</price>
    </entry>
    <entry>
        <seller_id>1</seller_id>
        <good_id>777</good_id>
        <amount>22</amount>
        <price>40778</price>
    </entry>
    <entry>
        <seller_id>1</seller_id>
        <good_id>888</good_id>
        <amount>19</amount>
        <price>157444</price>
    </entry>
    <entry>
        <seller_id>1</seller_id>
        <good_id>999</good_id>
        <amount>16</amount>
        <price>78086</price>
    </entry>
    <entry>
        <seller_id>2</seller_id>
        <good_id>111</good_id>
        <amount>16</amount>
        <price>33092</price>
    </entry>
    <entry>
        <seller_id>2</seller_id>
        <good_id>222</good_id>
        <amount>16</amount>
        <price>88821</price>
    </entry>
    <entry>
        <seller_id>2</seller_id>
        <good_id>333</good_id>
        <amount>23</amount>
        <price>112790</price>
    </entry>
    <entry>
        <seller_id>2</seller_id>
        <good_id>444</good_id>
        <amount>20</amount>
        <price>102519</price>
    </entry>
    <entry>
        <seller_id>2</seller_id>
        <good_id>555</good_id>
        <amount>25</amount>
        <price>55937</price>
    </entry>
    <entry>
        <seller_id>2</seller_id>
        <good_id>666</good_id>
        <amount>20</amount>
        <price>37426</price>
    </entry>
    <entry>
        <seller_id>2</seller_id>
        <good_id>777</good_id>
        <amount>27</amount>
        <price>33752</price>
    </entry>
    <entry>
        <seller_id>2</seller_id>
        <good_id>888</good_id>
        <amount>21</amount>
        <price>144254</price>
    </entry>
    <entry>
        <seller_id>2</seller_id>
        <good_id>999</good_id>
        <amount>28</amount>
        <price>73290</price>
    </entry>
    <entry>
        <seller_id>3</seller_id>
        <good_id>111</good_id>
        <amount>15</amount>
        <price>33615</price>
    </entry>
    <entry>
        <seller_id>3</seller_id>
        <good_id>222</good_id>
        <amount>18</amount>
        <price>113152</price>
    </entry>
    <entry>
        <seller_id>3</seller_id>
        <good_id>333</good_id>
        <amount>24</amount>
        <price>131855</price>
    </entry>
    <entry>
        <seller_id>3</seller_id>
        <good_id>444</good_id>
        <amount>18</amount>
        <price>105013</price>
    </entry>
    <entry>
        <seller_id>3</seller_id>
        <good_id>555</good_id>
        <amount>17</amount>
        <price>59009</price>
    </entry>
    <entry>
        <seller_id>3</seller_id>
        <good_id>666</good_id>
        <amount>20</amount>
        <price>38157</price>
    </entry>
    <entry>
        <seller_id>3</seller_id>
        <good_id>777</good_id>
        <amount>28</amount>
        <price>38326</price>
    </entry>
    <entry>
        <seller_id>3</seller_id>
        <good_id>888</good_id>
        <amount>20</amount>
        <price>102999</price>
    </entry>
    <entry>
        <seller_id>3</seller_id>
        <good_id>999</good_id>
        <amount>16</amount>
        <price>71066</price>
    </entry>
    <entry>
        <seller_id>4</seller_id>
        <good_id>111</good_id>
        <amount>17</amount>
        <price>35965</price>
    </entry>
    <entry>
        <seller_id>4</seller_id>
        <good_id>222</good_id>
        <amount>18</amount>
        <price>112828</price>
    </entry>
    <entry>
        <seller_id>4</seller_id>
        <good_id>333</good_id>
        <amount>16</amount>
        <price>107293</price>
    </entry>
    <entry>
        <seller_id>4</seller_id>
        <good_id>444</good_id>
        <amount>28</amount>
        <price>103824</price>
    </entry>
    <entry>
        <seller_id>4</seller_id>
        <good_id>555</good_id>
        <amount>28</amount>
        <price>53887</price>
    </entry>
    <entry>
        <seller_id>4</seller_id>
        <good_id>666</good_id>
        <amount>16</amount>
        <price>37728</price>
    </entry>
    <entry>
        <seller_id>4</seller_id>
        <good_id>777</good_id>
        <amount>23</amount>
        <price>34566</price>
    </entry>
    <entry>
        <seller_id>4</seller_id>
        <good_id>888</good_id>
        <amount>19</amount>
        <price>149645</price>
    </entry>
    <entry>
        <seller_id>4</seller_id>
        <good_id>999</good_id>
        <amount>23</amount>
        <price>68239</price>
    </entry>
    <entry>
        <seller_id>5</seller_id>
        <good_id>111</good_id>
        <amount>22</amount>
        <price>47283</price>
    </entry>
    <entry>
        <seller_id>5</seller_id>
        <good_id>222</good_id>
        <amount>28</amount>
        <price>93257</price>
    </entry>
    <entry>
        <seller_id>5</seller_id>
        <good_id>333</good_id>
        <amount>28</amount>
        <price>75790</price>
    </entry>
    <entry>
        <seller_id>5</seller_id>
        <good_id>444</good_id>
        <amount>24</amount>
        <price>99460</price>
    </entry>
    <entry>
        <seller_id>5</seller_id>
        <good_id>555</good_id>
        <amount>16</amount>
        <price>54108</price>
    </entry>
    <entry>
        <seller_id>5</seller_id>
        <good_id>666</good_id>
        <amount>16</amount>
        <price>40655</price>
    </entry>
    <entry>
        <seller_id>5</seller_id>
        <good_id>777</good_id>
        <amount>18</amount>
        <price>37318</price>
    </entry>
    <entry>
        <seller_id>5</seller_id>
        <good_id>888</good_id>
        <amount>22</amount>
        <price>166128</price>
    </entry>
    <entry>
        <seller_id>5</seller_id>
        <good_id>999</good_id>
        <amount>27</amount>
        <price>79821</price>
    </entry>
    <entry>
        <seller_id>6</seller_id>
        <good_id>111</good_id>
        <amount>25</amount>
        <price>44280</price>
    </entry>
    <entry>
        <seller_id>6</seller_id>
        <good_id>222</good_id>
        <amount>21</amount>
        <price>91456</price>
    </entry>
    <entry>
        <seller_id>6</seller_id>
        <good_id>333</good_id>
        <amount>19</amount>
        <price>105410</price>
    </entry>
    <entry>
        <seller_id>6</seller_id>
        <good_id>444</good_id>
        <amount>24</amount>
        <price>103500</price>
    </entry>
    <entry>
        <seller_id>6</seller_id>
        <good_id>555</good_id>
        <amount>22</amount>
        <price>59332</price>
    </entry>
    <entry>
        <seller_id>6</seller_id>
        <good_id>666</good_id>
        <amount>23</amount>
        <price>37363</price>
    </entry>
    <entry>
        <seller_id>6</seller_id>
        <good_id>777</good_id>
        <amount>20</amount>
        <price>41602</price>
    </entry>
    <entry>
        <seller_id>6</seller_id>
        <good_id>888</good_id>
        <amount>27</amount>
        <price>139917</price>
    </entry>
    <entry>
        <seller_id>6</seller_id>
        <good_id>999</good_id>
        <amount>27</amount>
        <price>77783</price>
    </entry>
    <entry>
        <seller_id>7</seller_id>
        <good_id>111</good_id>
        <amount>26</amount>
        <price>47084</price>
    </entry>
    <entry>
        <seller_id>7</seller_id>
        <good_id>222</good_id>
        <amount>26</amount>
        <price>85352</price>
    </entry>
    <entry>
        <seller_id>7</seller_id>
        <good_id>333</good_id>
        <amount>18</amount>
        <price>100051</price>
    </entry>
    <entry>
        <seller_id>7</seller_id>
        <good_id>444</good_id>
        <amount>28</amount>
        <price>102052</price>
    </entry>
    <entry>
        <seller_id>7</seller_id>
        <good_id>555</good_id>
        <amount>14</amount>
        <price>52919</price>
    </entry>
    <entry>
        <seller_id>7</seller_id>
        <good_id>666</good_id>
        <amount>22</amount>
        <price>38871</price>
    </entry>
    <entry>
        <seller_id>7</seller_id>
        <good_id>777</good_id>
        <amount>16</amount>
        <price>33378</price>
    </entry>
    <entry>
        <seller_id>7</seller_id>
        <good_id>888</good_id>
        <amount>28</amount>
        <price>142158</price>
    </entry>
    <entry>
        <seller_id>7</seller_id>
        <good_id>999</good_id>
        <amount>21</amount>
        <price>73304</price>
    </entry>
</stock>
